# PAGES

index:
  path: /
  controller: App\Controller\DefaultController::index

news:
  path: /news
  controller: App\Controller\NewsController::index

about:
  path: /about
  controller: App\Controller\AboutController::index

philosophy:
  path: /about/philosophy
  controller: App\Controller\PhilosophyController::index

directors:
  path: /about/directors
  controller: App\Controller\DirectorsController::index

teamApi:
  path: /api/team
  controller: App\Controller\TeamController::teamApi

teamMain:
  path: /about/team
  controller: App\Controller\TeamController::teamMain

teamIndex:
  path: /about/team/{id}
  controller: App\Controller\TeamController::teamIndex

portfolio:
  path: /portfolio
  controller: App\Controller\PortfolioController::index

contact:
  path: /contact
  controller: App\Controller\ContactController::index

#FOOTER
imprint:
  path: /imprint
  controller: App\Controller\ImprintController::index

legals:
  path: /legals
  controller: App\Controller\LegalsController::index

terms:
  path: /terms-of-use
  controller: App\Controller\TermsController::index
